import React, { useEffect, useState } from 'react';
import { Activity, Bell, Box, ChevronDown, Cloud, Layers3, Menu, Plus, RefreshCw, Search, Server, Settings2, ShieldCheck, Trash2, X, Zap } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:4000';
const demo = { applications: [{ _id: 'demo-1', name: 'checkout-api', repository: 'acme/checkout-api', image: 'ghcr.io/acme/checkout-api:v2.8.1', environment: 'production', status: 'healthy', replicas: 6, cluster: 'us-east-1-prod' }], deployments: [], alerts: [], metrics: [] };
const navGroups = [
  { label: 'Workspace', items: [{ name: 'Overview', icon: Layers3 }, { name: 'Applications', icon: Box }, { name: 'Deployments', icon: RefreshCw }, { name: 'Infrastructure', icon: Cloud }] },
  { label: 'Observe', items: [{ name: 'Metrics', icon: Activity }, { name: 'Alerts', icon: Bell }, { name: 'Logs', icon: Server }] }
];

function shortTime(value) { if (!value) return 'unknown'; const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 1 ? 'just now' : minutes < 60 ? `${minutes}m ago` : `${Math.floor(minutes / 60)}h ago`; }
function Status({ value }) { return <span className={`status status-${value}`}><i />{value === 'succeeded' ? 'Successful' : value === 'running' ? 'In progress' : value}</span>; }
function Empty({ children }) { return <div className="empty-state">{children}</div>; }

function AppForm({ onSubmit, onClose, busy }) {
  const [form, setForm] = useState({ name: '', repository: '', image: '', replicas: 1, cluster: 'local' });
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  return <div className="modal-backdrop"><form className="modal panel" onSubmit={(event) => { event.preventDefault(); onSubmit({ ...form, replicas: Number(form.replicas) }); }}><div className="panel-header"><div><div className="section-kicker">WORKSPACE</div><h2>New application</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={17} /></button></div><label>Name<input name="name" required value={form.name} onChange={update} placeholder="checkout-api" /></label><label>Repository<input name="repository" value={form.repository} onChange={update} placeholder="acme/checkout-api" /></label><label>Docker image<input name="image" value={form.image} onChange={update} placeholder="ghcr.io/acme/checkout-api:latest" /></label><div className="form-row"><label>Replicas<input name="replicas" type="number" min="0" required value={form.replicas} onChange={update} /></label><label>Cluster<input name="cluster" value={form.cluster} onChange={update} /></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? 'Creating...' : 'Create application'}</button></div></form></div>;
}

function AuthForm({ onSubmit, onClose, busy }) {
  const [form, setForm] = useState({ name: '', email: '', password: '' });
  const [registering, setRegistering] = useState(true);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  return <div className="modal-backdrop"><form className="modal panel" onSubmit={(event) => { event.preventDefault(); onSubmit(form, registering); }}><div className="panel-header"><div><div className="section-kicker">ACCESS</div><h2>{registering ? 'Create account' : 'Sign in'}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={17} /></button></div>{registering && <label>Name<input name="name" required value={form.name} onChange={update} /></label>}<label>Email<input name="email" type="email" required value={form.email} onChange={update} /></label><label>Password<input name="password" type="password" minLength="10" required value={form.password} onChange={update} /></label><button type="button" className="link-button" onClick={() => setRegistering(!registering)}>{registering ? 'Already have an account? Sign in' : 'Need an account? Register'}</button><div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? 'Working...' : registering ? 'Register' : 'Sign in'}</button></div></form></div>;
}

export default function App() {
  const [data, setData] = useState(demo);
  const [activeNav, setActiveNav] = useState('Overview');
  const [query, setQuery] = useState('');
  const [connected, setConnected] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [token, setToken] = useState(localStorage.getItem('deployment-monitor-token') || '');
  const [showAuth, setShowAuth] = useState(false);

  async function request(path, options = {}) {
    const response = await fetch(`${apiBase}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } });
    const body = response.status === 204 ? null : await response.json();
    if (!response.ok) throw new Error(body?.error || 'Request failed');
    return body;
  }
  async function refresh() {
    setRefreshing(true);
    try { setData({ ...demo, ...(await request('/api/overview')) }); setConnected(true); } catch { setConnected(false); } finally { setRefreshing(false); }
  }
  useEffect(() => { refresh(); const interval = window.setInterval(refresh, 30000); return () => window.clearInterval(interval); }, []);
  async function createApplication(form) { setBusy(true); setMessage(''); try { await request('/api/applications', { method: 'POST', body: JSON.stringify(form) }); setShowForm(false); setActiveNav('Applications'); await refresh(); } catch (error) { setMessage(`${error.message}. Register or log in first, then try again.`); } finally { setBusy(false); } }
  async function deleteApplication(id) { if (!window.confirm('Delete this application and its history?')) return; try { await request(`/api/applications/${id}`, { method: 'DELETE' }); await refresh(); } catch (error) { setMessage(error.message); } }
  async function deployApplication(item) { const image = window.prompt('Container image for this deployment:', item.image || ''); if (!image) return; try { await request(`/api/applications/${item._id}/deployments`, { method: 'POST', body: JSON.stringify({ image, replicas: item.replicas }) }); setActiveNav('Deployments'); await refresh(); } catch (error) { setMessage(error.message); } }
  async function acknowledge(id) { try { await request(`/api/alerts/${id}`, { method: 'PATCH', body: JSON.stringify({ status: 'acknowledged' }) }); await refresh(); } catch (error) { setMessage(error.message); } }
  async function authenticate(form, registering) {
    setBusy(true); setMessage('');
    try { const result = await request(`/api/auth/${registering ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(form) }); const nextToken = registering ? (await request('/api/auth/login', { method: 'POST', body: JSON.stringify({ email: form.email, password: form.password }) })).token : result.token; localStorage.setItem('deployment-monitor-token', nextToken); setToken(nextToken); setShowAuth(false); await refresh(); } catch (error) { setMessage(error.message); } finally { setBusy(false); }
  }

  const applications = data.applications || [];
  const visibleApps = applications.filter((item) => `${item.name} ${item.repository} ${item.cluster}`.toLowerCase().includes(query.toLowerCase()));
  const chartData = (data.metrics?.length ? data.metrics : Array.from({ length: 10 }, (_, index) => ({ cpuPercent: 35 + index * 2, memoryMiB: 400 + index * 8 }))).map((item, index) => ({ time: `${index * 5}m`, cpu: Math.round(item.cpuPercent), memory: Math.round(item.memoryMiB / 12) }));
  const heading = activeNav === 'Overview' ? 'Good morning, Maria.' : activeNav;

  function Table({ children }) { return <div className="panel table-panel"><div className="panel-header"><div><div className="section-kicker">LIVE WORKSPACE DATA</div><h2>{heading}</h2></div><button className="button button-secondary" onClick={refresh}><RefreshCw size={14} className={refreshing ? 'spin' : ''} />Refresh</button></div>{children}</div>; }
  function Applications() { return <Table><div className="table-actions page-tools"><label className="search-box"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter applications" /></label><button className="button button-primary" onClick={() => setShowForm(true)}><Plus size={15} />New application</button></div><div className="table-scroll"><table><thead><tr><th>APPLICATION</th><th>STATUS</th><th>ENVIRONMENT</th><th>REPLICAS</th><th>IMAGE</th><th>ACTIONS</th></tr></thead><tbody>{visibleApps.map((item) => <tr key={item._id}><td><strong>{item.name}</strong><span className="table-subtext">{item.repository || 'No repository'}</span></td><td><Status value={item.status} /></td><td>{item.environment}</td><td>{item.replicas}</td><td className="mono-tag">{item.image || 'Not configured'}</td><td><button className="button button-secondary compact-button" onClick={() => deployApplication(item)}>Deploy</button><button className="icon-button" onClick={() => deleteApplication(item._id)} aria-label={`Delete ${item.name}`}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div>{!visibleApps.length && <Empty>No applications match this filter.</Empty>}</Table>; }
  function Deployments() { return <Table><div className="table-scroll"><table><thead><tr><th>APPLICATION</th><th>IMAGE</th><th>STATUS</th><th>TRIGGERED BY</th><th>CREATED</th></tr></thead><tbody>{data.deployments.map((item) => <tr key={item._id}><td>{item.application?.name || 'Application'}</td><td className="mono-tag">{item.image}</td><td><Status value={item.status} /></td><td>{item.triggeredBy}</td><td>{shortTime(item.createdAt)}</td></tr>)}</tbody></table></div>{!data.deployments.length && <Empty>No deployments recorded yet.</Empty>}</Table>; }
  function Alerts() { return <Table><div className="table-scroll"><table><thead><tr><th>TYPE</th><th>MESSAGE</th><th>STATUS</th><th>TRIGGERED</th><th>ACTION</th></tr></thead><tbody>{data.alerts.map((item) => <tr key={item._id}><td><Zap size={14} /> {item.type}</td><td>{item.message}</td><td>{item.status}</td><td>{shortTime(item.triggeredAt)}</td><td>{item.status === 'firing' && <button className="button button-secondary compact-button" onClick={() => acknowledge(item._id)}>Acknowledge</button>}</td></tr>)}</tbody></table></div>{!data.alerts.length && <Empty>No active alerts.</Empty>}</Table>; }
  function Metrics() { return <Table><div className="chart-wrap metrics-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><XAxis dataKey="time" /><YAxis /><Tooltip /><Area dataKey="cpu" stroke="#286c5c" fill="#d3e4d9" /><Area dataKey="memory" stroke="#db9a52" fill="#f2dfc9" /></AreaChart></ResponsiveContainer></div><div className="table-scroll"><table><thead><tr><th>CPU</th><th>MEMORY</th><th>NETWORK</th><th>CONTAINER</th><th>RESTARTS</th><th>RECORDED</th></tr></thead><tbody>{data.metrics.map((item, index) => <tr key={item._id || index}><td>{Math.round(item.cpuPercent)}%</td><td>{Math.round(item.memoryMiB)} MiB</td><td>{Math.round(item.networkMiB || 0)} MiB</td><td>{item.containerStatus || 'running'}</td><td>{item.restartCount || 0}</td><td>{shortTime(item.recordedAt)}</td></tr>)}</tbody></table></div>{!data.metrics.length && <Empty>No metrics recorded yet.</Empty>}</Table>; }
  function StaticPage({ title, text }) { return <Table><div className="detail-grid"><article><Cloud size={22} /><strong>{title}</strong><p>{text}</p></article><article><ShieldCheck size={22} /><strong>{connected ? 'API connected' : 'Demo mode'}</strong><p>{connected ? 'Live data is being read from MongoDB through the API.' : 'Start the API and MongoDB to view live records.'}</p></article></div></Table>; }
  function Content() { if (activeNav === 'Applications') return <Applications />; if (activeNav === 'Deployments') return <Deployments />; if (activeNav === 'Metrics') return <Metrics />; if (activeNav === 'Alerts') return <Alerts />; if (activeNav === 'Infrastructure') return <StaticPage title="Infrastructure" text="Kubernetes cluster capacity and node health will appear here when the cluster adapter is connected." />; if (activeNav === 'Logs') return <StaticPage title="Logs" text="Container log streaming requires a Kubernetes or Docker log collector." />; return <><section className="metric-grid"><article className="metric-card"><strong>Applications</strong><div className="metric-value">{applications.length}</div></article><article className="metric-card"><strong>Healthy services</strong><div className="metric-value">{applications.filter((item) => item.status === 'healthy').length}</div></article><article className="metric-card"><strong>Deployments</strong><div className="metric-value">{data.deployments.length}</div></article><article className="metric-card"><strong>Active alerts</strong><div className="metric-value">{data.alerts.filter((item) => item.status === 'firing').length}</div></article></section><Metrics /></>; }

  return <div className="shell"><aside className="sidebar"><a className="brand" href="#overview"><span className="brand-mark"><span /><span /><span /></span><span className="brand-name">fieldnote</span><span className="brand-caption">OPS</span></a><div className="workspace-switch"><div className="workspace-avatar">A</div><div className="workspace-copy"><strong>Acme platform</strong><span>Engineering</span></div><ChevronDown size={15} /></div><div className="sidebar-nav">{navGroups.map((group) => <div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(({ name, icon: Icon }) => <button className={`nav-item ${activeNav === name ? 'selected' : ''}`} key={name} onClick={() => setActiveNav(name)}><Icon size={17} /><span>{name}</span></button>)}</div>)}</div><div className="sidebar-bottom"><button className="nav-item"><Settings2 size={17} /><span>Settings</span></button></div></aside><main className="main-area"><header className="topbar"><div className="breadcrumbs"><span>Acme platform</span><span>/</span><strong>{activeNav}</strong></div><div className="topbar-actions"><div className="api-state"><span className={connected ? 'connected' : 'demo-mode'} />{connected ? 'API connected' : 'Sample data'}</div><button className="button button-secondary auth-button" onClick={() => setShowAuth(true)}>{token ? 'Account' : 'Sign in'}</button><button className="icon-button mobile-menu" aria-label="Open navigation"><Menu size={18} /></button><div className="top-avatar">MC</div></div></header><div className="page-content"><section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line" />PLATFORM OPERATIONS</div><h1>{heading}</h1><p>Manage applications, deployments, infrastructure, and observability.</p></div><div className="heading-actions"><button className="button button-secondary" onClick={refresh}><RefreshCw size={15} />Refresh</button><button className="button button-primary" onClick={() => setShowForm(true)}><Plus size={16} />New application</button></div></section>{message && <div className="notice">{message}</div>}<Content /></div></main>{showForm && <AppForm onSubmit={createApplication} onClose={() => setShowForm(false)} busy={busy} />}{showAuth && <AuthForm onSubmit={authenticate} onClose={() => setShowAuth(false)} busy={busy} />}</div>;
}
